### PR TITLE
Set error_reporting -1 to catch all errors

### PR DESCRIPTION
**Pull request by rogeriopradoj**
As http://www.phptherightway.com/#error_reporting and http://www.php.net/manual/en/function.error-reporting.php

### CODE REVIEW

**Comment by williancarminato** [comment]
Thanks @rogeriopradoj !

**Comment by rogeriopradoj** [comment]
My pleasure!

A question: what are you building, guys?

**Comment by williancarminato** [comment]
We're on Hack Battle doing a quiz with Deezer API.

https://www.hackerleague.org/hackathons/kings-of-code-hack-battle-at-tnw-latin-america/hacks/whats-the-music

**Comment by rogeriopradoj** [comment]
Oh, nice. Good luck on that!

**Pull request merged**
